services:
    application:
        build:
            context: .
            dockerfile: dockerfiles/php/Dockerfile
        image: application
        container_name: application
        tty: true
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
        networks:
            - laravel_app
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_app
    db:
        image: mysql:latest
        container_name: mysql_container
        volumes:
            - mysql_container:/var/lib/mysql
        ports:
            - "3306:3306"
        expose:
            - '3306'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: teste
            MYSQL_TCP_PORT: 3306
        networks:
            - laravel_app
volumes:
    mysql_container:
        driver: local
networks:
    laravel_app:
        driver: bridge
